#!/usr/bin/env bash

# Use this script to create a sample example which creats a tree 
# and saves it into a vtk file.
# 
# Usage:
#   ./create_example name [config]
#

# creates a .pro file 
function create_pro() {
cat > $1/$1.pro << EOF
# --------------------------------------------------------------
# qmake config file for example $1
# --------------------------------------------------------------
CONFIG += 2d

include(../../config/$2.pri)
include(../../config/libparcasl.pri)

CONFIG(2d, 2d|3d): {
  TARGET = $1_2d
  SOURCES += main_2d.cpp
}

CONFIG(3d, 2d|3d): {
  TARGET = $1_3d
  SOURCES += main_3d.cpp
}

EOF
}

# creates a sample main_2d.cpp and main_3d.cpp
function create_main() {
cat > $1/main_2d.cpp << EOF
/* 
 * Title: $1
 * Description:
 * Author: $(git config user.name)
 * Date Created: $(date +%m-%d-%Y)
 */

#ifndef P4_TO_P8
#include <src/my_p4est_utils.h>
#include <src/my_p4est_vtk.h>
#include <src/my_p4est_nodes.h>
#include <src/my_p4est_tools.h>
#include <src/my_p4est_refine_coarsen.h>
#include <src/my_p4est_log_wrappers.h>
#include <src/my_p4est_node_neighbors.h>
#include <src/my_p4est_macros.h>
#else
#include <src/my_p8est_utils.h>
#include <src/my_p8est_vtk.h>
#include <src/my_p8est_nodes.h>
#include <src/my_p8est_tools.h>
#include <src/my_p8est_refine_coarsen.h>
#include <src/my_p8est_log_wrappers.h>
#include <src/my_p8est_node_neighbors.h>
#include <src/my_p8est_macros.h>
#endif

#include <src/Parser.h>
#include <src/CASL_math.h>

using namespace std;

int main(int argc, char** argv) {
  
  // prepare parallel enviroment
  mpi_environment_t mpi;
  mpi.init(argc, argv);

  // stopwatch
  parStopWatch w;
  w.start("Running example: $1");

  // p4est variables
  p4est_t*              p4est;
  p4est_nodes_t*        nodes;
  p4est_ghost_t*        ghost;
  p4est_connectivity_t* conn;
  my_p4est_brick_t      brick;

  // domain size information
  const int n_xyz []      = {1, 1, 1};
  const double xyz_min [] = {-1, -1, -1};
  const double xyz_max [] = { 1,  1,  1};
  conn = my_p4est_brick_new(n_xyz, xyz_min, xyz_max, &brick);

  // create the forest
  p4est = my_p4est_new(mpi.comm(), conn, 0, NULL, NULL);

  // refine based on distance to a level-set
#ifdef P4_TO_P8
  struct:CF_3{
    double operator()(double x, double y, double z) const {
      return 0.5 - sqrt(SQR(x) + SQR(y) + SQR(z));
    }
  } circle;
#else
  struct:CF_2{
    double operator()(double x, double y) const {
      return 0.5 - sqrt(SQR(x) + SQR(y));
    }
  } circle;
#endif

  splitting_criteria_cf_t sp(3, 8, &circle);
  p4est->user_pointer = &sp;
  my_p4est_refine(p4est, P4EST_TRUE, refine_levelset_cf, NULL);

  // partition the forest
  my_p4est_partition(p4est, P4EST_TRUE, NULL);

  // create ghost layer
  ghost = my_p4est_ghost_new(p4est, P4EST_CONNECT_FULL);

  // create node structure
  nodes = my_p4est_nodes_new(p4est, ghost);

  // save the grid into vtk
  my_p4est_vtk_write_all(p4est, nodes, ghost,
                         P4EST_TRUE, P4EST_TRUE,
                         0, 0, "$1");

  // destroy the structures
  p4est_nodes_destroy(nodes);
  p4est_ghost_destroy(ghost);
  p4est_destroy      (p4est);
  my_p4est_brick_destroy(conn, &brick);

  w.stop(); w.read_duration();
}

EOF

cat > $1/main_3d.cpp << EOF
#include <src/my_p4est_to_p8est.h>
#include "main_2d.cpp"

EOF
}

if [[ "$#" -ne 1 ]]; then
    echo "useage: $(basename "$0") name [config]\n"\
         "'name'  : name of the example file (will be skipped if already exist)\n"\
         "'config': configuration to be used for finding dependencies (defaults to homebrew)"
else
	name=$1
  config=$2

  # check if a config is set, if not set it to homebrew 
  if [[ -z $config ]]; then
    config="homebrew"
  fi

  # create a new example only if one does not exist with the same name
	if [[ ! -e $name ]]; then
		mkdir $name
    create_pro $name $config
    create_main $name
	else
		echo "Example '$name' already exists. Please choose another name."
		exit 1
	fi	
fi
