#!/usr/bin/env bash

# Use this script to generate a pro file for an existing example
# 
# Usage:
#   ./newprofile name
#

# creates a .pro file 
function create_pro() {
cat > $1.pro << EOF
# --------------------------------------------------------------
# This is a qmake script for generating makefiles. Please read
# this short comment before changing this file. In particular,
#
#     *** DO NOT ADD SYSTEM DEPENDENT VARIABLES HERE ***
#
# Following build systems are supported:
#   * macx (default)
#   * linux
#   * stampede
#
# To use either of these systems, please pass in the correct
# value to qmake, e.g. to build for stamepde system:
#   qmake example.pro CONFIG+="stampede"
#
#           *** DO NOT ADD BUILD CONFIG HERE ***
#
# Instead pass the variable in terminal or through project
# settings in QtCreator IDE.
# --------------------------------------------------------------
CONFIG += 2d
include(../../qmake/libparcasl.pri)

CONFIG(2d, 2d|3d): {
  TARGET   = $1_2d
  SOURCES += main_2d.cpp
}

CONFIG(3d, 2d|3d): {
  TARGET   = $1_3d
  SOURCES += main_3d.cpp
}

EOF
}

if [[ "$#" -ne 1 ]]; then
    echo "useage: ./$(basename "$0") example"
else
  name=$1

  # create a new example only if one does not exist with the same name
  if [[ -e $name ]]; then
    cd $name
    if [[ ! -e $name.pro ]]; then
      create_pro $name
    else
      echo "ERROR: Profile '$name.pro' already exists. Please choose another name."
      exit 1
    fi
  else
    echo "ERROR: Example '$name' does not exist. Please choose an existing example."
    exit 1
  fi  
fi
